/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_oop_kendaraan;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gdkri
 */
public class FormMobil extends javax.swing.JFrame {
    // Logger untuk mencatat error dan aktivitas aplikasi
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMobil.class.getName());

    /**
     * Creates new form FormMobil
     */
    
    
    // Menyimpan indeks baris tabel yang dipilih
    private int selectedRow = -1;
    
    
    // Constructor form, dijalankan saat form dibuka
    public FormMobil() {
        initComponents();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Merk");
        model.addColumn("Warna");
        model.addColumn("Tahun");
        model.addColumn("Kecepatan");
        model.addColumn("Jumlah Pintu");

        tblMobil.setModel(model);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMerk = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        txtKecepatan = new javax.swing.JTextField();
        txtPintu = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Merk Mobil");

        jLabel2.setText("Warna Mobil");

        jLabel3.setText("Tahun");

        jLabel4.setText("Kecepatan");

        jLabel5.setText("Jumlah Pintu");

        txtMerk.addActionListener(this::txtMerkActionPerformed);

        btnSimpan.setBackground(new java.awt.Color(0, 153, 51));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        tblMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMobilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMobil);

        btnReset.setBackground(new java.awt.Color(102, 102, 102));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPintu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtKecepatan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWarna)
                            .addComponent(txtTahun)
                            .addComponent(txtMerk))))
                .addGap(408, 408, 408))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKecepatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPintu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnReset)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String merk = txtMerk.getText();
    String warna = txtWarna.getText();
    int tahun = Integer.parseInt(txtTahun.getText());
    int kecepatan = Integer.parseInt(txtKecepatan.getText());
    int pintu = Integer.parseInt(txtPintu.getText());

    DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();

    // =========================
    // UPDATE MODE
    // =========================
    if (selectedRow != -1 && selectedRow < model.getRowCount()) {

        int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

        try {
            java.sql.Connection conn = Koneksi.getConnection();

            String sql = "UPDATE mobil SET merk=?, warna=?, tahun=?, kecepatan=?, pintu=? WHERE id=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, merk);
            pst.setString(2, warna);
            pst.setInt(3, tahun);
            pst.setInt(4, kecepatan);
            pst.setInt(5, pintu);
            pst.setInt(6, id);

            pst.executeUpdate();

            // update tabel UI
            model.setValueAt(merk, selectedRow, 1);
            model.setValueAt(warna, selectedRow, 2);
            model.setValueAt(tahun, selectedRow, 3);
            model.setValueAt(kecepatan, selectedRow, 4);
            model.setValueAt(pintu, selectedRow, 5);

            selectedRow = -1;

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Update DB Error: " + e.getMessage());
        }

    } 
    // =========================
    // INSERT MODE
    // =========================
    else {

        try {
            java.sql.Connection conn = Koneksi.getConnection();

            String sql = "INSERT INTO mobil (merk, warna, tahun, kecepatan, pintu) VALUES (?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);

            pst.setString(1, merk);
            pst.setString(2, warna);
            pst.setInt(3, tahun);
            pst.setInt(4, kecepatan);
            pst.setInt(5, pintu);

            pst.executeUpdate();

            java.sql.ResultSet rs = pst.getGeneratedKeys();

            int id = 0;
            if (rs.next()) {
                id = rs.getInt(1);
            }

            model.addRow(new Object[]{
                id,
                merk,
                warna,
                tahun,
                kecepatan,
                pintu
            });

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "DB Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMerk.setText("");
        txtWarna.setText("");
        txtTahun.setText("");
        txtKecepatan.setText("");
        txtPintu.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();

        selectedRow = tblMobil.getSelectedRow();

        if (selectedRow != -1) {

    try {
        java.sql.Connection conn = Koneksi.getConnection();

        String sql = "DELETE FROM mobil WHERE id=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        int id = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        pst.setInt(1, id);

        pst.executeUpdate();

        model.removeRow(selectedRow);
        selectedRow = -1;

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Delete DB Error: " + e.getMessage());
    }

} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu data di tabel!");
}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
   selectedRow = tblMobil.getSelectedRow();

    if (selectedRow != -1) {
        // Mulai dari kolom 1 (Merk) karena kolom 0 adalah ID
        txtMerk.setText(tblMobil.getValueAt(selectedRow, 1).toString());
        txtWarna.setText(tblMobil.getValueAt(selectedRow, 2).toString());
        txtTahun.setText(tblMobil.getValueAt(selectedRow, 3).toString());
        txtKecepatan.setText(tblMobil.getValueAt(selectedRow, 4).toString());
        txtPintu.setText(tblMobil.getValueAt(selectedRow, 5).toString());
    }
    }//GEN-LAST:event_formMouseClicked

    private void tblMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMobilMouseClicked
        selectedRow = tblMobil.getSelectedRow();

        if (selectedRow != -1) {
            // Kolom 0 adalah ID, jadi kita mulai dari kolom 1 untuk Merk
            txtMerk.setText(tblMobil.getValueAt(selectedRow, 1).toString());
            txtWarna.setText(tblMobil.getValueAt(selectedRow, 2).toString());
            txtTahun.setText(tblMobil.getValueAt(selectedRow, 3).toString());
            txtKecepatan.setText(tblMobil.getValueAt(selectedRow, 4).toString());
            txtPintu.setText(tblMobil.getValueAt(selectedRow, 5).toString());
        }
    }//GEN-LAST:event_tblMobilMouseClicked

    private void txtMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerkActionPerformed
        private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();
        model.setRowCount(0); 

        try {
            java.sql.Connection conn = Koneksi.getConnection();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT * FROM mobil");
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("merk"),
                    rs.getString("warna"),
                    rs.getInt("tahun"),
                    rs.getInt("kecepatan"),
                    rs.getInt("pintu")
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMobil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblMobil;
    private javax.swing.JTextField txtKecepatan;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtPintu;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
